num1 = int(input("Enter a number: "))
num2 = int(input("Enter a second number: "))
print(str(num1) +" + " + str(num2) + " = " + str(num1 + num2))
print(str(num1) +" * " + str(num2) + " = " + str(num1 * num2))
print(str(num1) +" / " + str(num2) + " = " + str(num1 / num2))
print(str(num1) +" % " + str(num2) + " = " + str(num1 % num2))
print(str(num1) +" ^ " + str(num2) + " = " + str(num1 ** num2))
